/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // The dev badge sits on top of the bottom nav in the 390px frame.
  devIndicators: false,
  async headers() {
    return [
      {
        // Generated by scripts/build_web_data.py. Content changes only when we re-run it,
        // so the CDN can hold it and the PWA can serve it offline.
        source: "/data/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=300, stale-while-revalidate=86400" }],
      },
      {
        source: "/photos/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/sw.js",
        headers: [
          { key: "Cache-Control", value: "no-cache" },
          { key: "Service-Worker-Allowed", value: "/" },
        ],
      },
    ];
  },
};

export default nextConfig;
